### PR TITLE
Run Command tests for .exec_() as well

### PR DESCRIPTION
**Pull request by JayH5**
This won't increase coverage because I can't get Coverage to work on a Python process that execs.

### CODE REVIEW

**Comment by jerith** [comment]
Would it be cleaner to use a pytest parameterised fixture for this? http://doc.pytest.org/en/latest/fixture.html#fixture-parametrize

**Comment by jerith** [comment]
There's http://coverage.readthedocs.io/en/coverage-4.2/subprocess.html for coverage, but it's horrible. Let's not bother with it.

**Comment by JayH5** [comment]
I did actually try that a few months ago. Couldn't get it to work. I think it might be impossible when `exec`-ing as the Python process is replaced and never gets a chance to report coverage. But I could've easily got something wrong.

**Review by jerith — APPROVED** [review]
:+1:

**Pull request merged**
